name: baseapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  gdpr_dialog: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fondo.jpg
    - assets/logo.png
    - assets/restaurante.png
    - assets/usuario.png
    - assets/usuario2.png
    - assets/correo.png
    - assets/password.png
    - assets/google.png
