name: PerfectConnection
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  gdpr_dialog: ^2.1.1
  flutter_native_splash: ^2.3.5
  flutter_stripe: ^9.5.0+1
  image_picker: ^1.0.4
  shimmer: ^3.0.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.2
  rxdart: ^0.27.7
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: 'assets/logo.png'
  android: true